all: exercise1 exercise2 exercise3

exercise1: exercise1.c
	gcc -o exercise1 exercise1.c

exercise2: exercise1.c
	gcc -std=c99 -o exercise2 exercise2.c

exercise3: exercise3.c
	gcc -o exercise3 exercise3.c
