all: exercise1 exercise2 exercise3

exercise1: exercise1.c
	gcc -c -o magic_function.o magic_function.c
	gcc -o exercise1 exercise1.c magic_function.o

exercise2: exercise2.c
	gcc -o exercise2 exercise2.c

exercise3: exercise3.c
	gcc -o exercise3 exercise3.c
